# code: language=ansible
---
- name: Install Docker and Form Docker Swarm
  hosts: all
  gather_facts: true
  roles:
    - role: install
      become: true
    - role: swarm

- name: Install and Start Cloudflare Tunnel
  hosts: tunnel_hosts
  gather_facts: true
  roles:
    - role: cf_tunnel
