# code: language=ansible
---
- name: Install Docker and Form Docker Swarm
  hosts: swarm_managers,swarm_workers
  gather_facts: true
  roles:
    - role: docker
      become: true
    - role: swarm

- name: Install and Start Cloudflare Tunnel
  hosts: tunnel_hosts
  gather_facts: true
  roles:
    - role: docker
      become: true
    - role: cf_tunnel
