# code: language=ansible
---
- name: Check if Docker Swarm is already initialized
  ansible.builtin.command:
    cmd: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
  register: swarm_status
  changed_when: false

- name: Create group initialized_managers
  ansible.builtin.add_host:
    name: '{{ item }}'
    groups: initialized_managers
  loop: '{{ groups["swarm_managers"] }}'
  when: hostvars[item]['swarm_status'].stdout == 'active'

- name: Create group uninitialized_managers
  ansible.builtin.add_host:
    name: '{{ item }}'
    groups: uninitialized_managers
  loop: '{{ groups["swarm_managers"] }}'
  when: hostvars[item]['swarm_status'].stdout == 'inactive'

- name: Create group initialized_workers
  ansible.builtin.add_host:
    name: '{{ item }}'
    groups: initialized_workers
  loop: '{{ groups["swarm_workers"] }}'
  when: hostvars[item]['swarm_status'].stdout == 'active'

- name: Create group uninitialized_workers
  ansible.builtin.add_host:
    name: '{{ item }}'
    groups: uninitialized_workers
  loop: '{{ groups["swarm_workers"] }}'
  when: hostvars[item]['swarm_status'].stdout == 'inactive'
# - name: Initialize Docker Swarm
#   ansible.builtin.command:
#     cmd: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
#   when: groups['initialized_manager'] | length == 0 and inventory_hostname == groups['uninitialized_managers'][0]
#   changed_when: false

# - name: Add the initialized manager to the initialized_managers group
#   ansible.builtin.add_host:
#     name: "{{ groups['uninitialized_managers'][0] }}"
#     groups: initialized_managers
#   when: groups['initialized_manager'] | length == 0 and inventory_hostname == groups['uninitialized_managers'][0]

# - name: Get Docker Swarm manager join token
#   ansible.builtin.command:
#     cmd: docker swarm join-token manager -q
#   register: manager_join_token
#   when: groups['initialized_manager'] | length > 0 and inventory_hostname == groups['initialized_manager'][0]
#   changed_when: false

# - name: Get Docker Swarm worker join token
#   ansible.builtin.command:
#     cmd: docker swarm join-token worker -q
#   register: worker_join_token
#   when: groups['initialized_manager'] | length > 0 and inventory_hostname == groups['initialized_manager'][0] and groups['uninitialized_workers'] | length > 0
#   changed_when: false
# - name: Set join token fact
#   ansible.builtin.set_fact:
#     join_token: '{{ join_token.stdout }}'

# - name: Join Docker Swarm
#   ansible.builtin.command:
#     cmd: docker swarm join --token {{ join_token }} {{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}:2377
#   when: inventory_hostname not in groups['swarm_managers']
#   changed_when: false
