# code: language=ansible
---
- name: Check if Docker Swarm is already initialized on manager nodes
  ansible.builtin.command:
    cmd: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
  register: swarm_status
  when: inventory_hostname in groups['swarm_managers']
  changed_when: false

- name: Check if Docker Swarm is already initialized on worker nodes
  ansible.builtin.command:
    cmd: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
  register: swarm_status
  when: inventory_hostname in groups['swarm_workers']
  changed_when: false

- name: Create group initialized_managers
  ansible.builtin.add_host:
    name: '{{ item }}'
    groups: initialized_managers
  loop: "{{ groups['swarm_managers'] }}"
  when: inventory_hostname in group['swarm_manager'] and swarm_status.stdout == 'active'

- name: Create group initialized_workers
  ansible.builtin.add_host:
    name: '{{ item }}'
    groups: initialized_workers
  loop: "{{ groups['swarm_workers'] }}"
  when: inventory_hostname in groups['swarm_workers'] and swarm_status.stdout == 'active'

- name: Initialize Docker Swarm
  ansible.builtin.command:
    cmd: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
  when: inventory_hostname == groups['swarm_managers'] and length(groups['initialized_manager']) == 0
  changed_when: false

- name: Get Docker Swarm manager join token
  ansible.builtin.command:
    cmd: docker swarm join-token manager -q
  register: manager_join_token
  when: length(groups['initialized_manager']) > 0 and inventory_hostname == groups['initialized_manager'][0]
  changed_when: false

- name: Get Docker Swarm worker join token
  ansible.builtin.command:
    cmd: docker swarm join-token worker -q
  register: worker_join_token
  when: inventory_hostname == groups['swarm_manager_operational'][0]
  changed_when: false

- name: Set join token fact
  ansible.builtin.set_fact:
    join_token: '{{ join_token.stdout }}'

- name: Join Docker Swarm
  ansible.builtin.command:
    cmd: docker swarm join --token {{ join_token }} {{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}:2377
  when: inventory_hostname not in groups['swarm_managers']
  changed_when: false
