# code: language=ansible
---
- name: Check if Docker Swarm is already initialized on manager nodes
  ansible.builtin.command:
    cmd: docker info --format '{{ '{{.Swarm.LocalNodeState}}' }}'
  register: swarm_status
  changed_when: false

- name: Create Docker Swarm manager operational group
  ansible.builtin.add_host:
    hostname: '{{ item }}'
    groups: swarm_manager_operational
  with_items: '{{ groups["swarm_managers"] }}'
  when: inventory_hostname in groups['swarm_managers'] and swarm_status.stdout == 'active'

- name: Create Docker Swarm manager non-operational group
  ansible.builtin.add_host:
    hostname: '{{ item }}'
    groups: swarm_manager_non_operational
  with_items: '{{ groups["swarm_managers"] }}'
  when: inventory_hostname in groups['swarm_managers'] and swarm_status.stdout == 'inactive'

- name: Create Docker Swarm worker operational group
  ansible.builtin.add_host:
    hostname: '{{ item }}'
    groups: swarm_worker_operational
  with_items: '{{ groups["swarm_workers"] }}'
  when: inventory_hostname in groups['swarm_workers'] and swarm_status.stdout == 'active'

- name: Create Docker Swarm worker non-operational group
  ansible.builtin.add_host:
    hostname: '{{ item }}'
    groups: swarm_worker_non_operational
  with_items: '{{ groups["swarm_workers"] }}'
  when: inventory_hostname in groups['swarm_workers'] and swarm_status.stdout == 'inactive'

- name: Initialize Docker Swarm
  ansible.builtin.command:
    cmd: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
  # inventory_hostname needs to come first, ansible will try to evalue swarm_status.stdout on all hosts
  # causing an err on worker nodes
  when: inventory_hostname == groups['swarm_managers'][0] and swarm_status.stdout == 'inactive'
  changed_when: false
# - name: Get Docker Swarm join token
#   ansible.builtin.command:
#     cmd: docker swarm join-token worker -q
#   register: join_token
#   when: inventory_hostname == groups['swarm_managers'][0]
#   changed_when: false

# - name: Set join token fact
#   ansible.builtin.set_fact:
#     join_token: '{{ join_token.stdout }}'

# - name: Join Docker Swarm
#   ansible.builtin.command:
#     cmd: docker swarm join --token {{ join_token }} {{ hostvars[groups['swarm_managers'][0]]['ansible_default_ipv4']['address'] }}:2377
#   when: inventory_hostname not in groups['swarm_managers']
#   changed_when: false
