# code: language=ansible
---
- name: Install prerequisites
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - wireguard

- name: Check if the Wireguard Private Key Exists
  ansible.builtin.stat:
    path: /etc/wireguard/privatekey
  register: wireguard_privatekey

- name: Generate Wireguard Private Key & Public
  ansible.builtin.shell: |
    set -o pipefail
    wg genkey | tee /etc/wireguard/privatekey | wg pubkey | tee /etc/wireguard/publickey
  when: not wireguard_privatekey.stat.exists
  changed_when: false

- name: Get Base64 Encodd Wireguard Private Key on the Remote Server
  ansible.builtin.slurp:
    src: /etc/wireguard/privatekey
  register: wireguard_privatekey_base64

- name: Create Wireguard Server Configuration
  ansible.builtin.template:
    src: '{{ role_path }}/templates/wireguard.conf.j2'
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0600'
  vars:
    encoded_wireguard_private_key: '{{ wireguard_privatekey_base64.content }}'
    wireguard_ip_address_cidr: '172.16.0.0/24'
